/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/car_rig.glb 
Author: sameer.malik1 (https://sketchfab.com/sameer.malik1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-rig-166cdbd574934c86b8237ad6717d70ae
Title: Car_rig
*/

import React, { useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";

export default function Model({ metalness, roughness, props, scale, setColor, color }) {
  const { nodes, materials } = useGLTF("/car_rig.glb");

  const [hoveredMesh, setHoveredMesh] = useState(null);
  const [componentName, setComponentName] = useState(null);

  useEffect(() => {
    for (let ele in materials) {
      materials[ele].metalness = metalness;
      materials[ele].roughness = roughness;
      materials[ele].normalMap = null;
    }
  }, [metalness, roughness]);

  const handlePointerOver = (e) => {
    e.stopPropagation();
    console.log(e);
    if (color) {
      setHoveredMesh(e);
    }
  };

  useEffect(() => {
    console.log(hoveredMesh?.object?.material?.name);
    if (hoveredMesh !== null) {
      setComponentName(hoveredMesh?.object?.material?.name);
      setHoveredMesh(null);
    }
  }, [hoveredMesh]);

  const handlePointerOut = () => {
    setHoveredMesh(null);
  };

  useEffect(() => {
    console.log("rededer...");
    if (componentName) {
      materials[componentName].color = new Color(color); // Red color
      setColor(null);
      setComponentName(null);
    }
  }, [materials, color, hoveredMesh]);

  return (
    <group {...props} scale={scale} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.701, -0.018, 0.417]} scale={0.05}>
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface103_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface104_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface105_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface106_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface107_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface108_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface109_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface110_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface111_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface112_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface113_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface114_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface115_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface116_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface117_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface118_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface119_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface120_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface121_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface122_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface123_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface124_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface125_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface126_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface127_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface128_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface129_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface130_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface131_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface132_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface133_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface134_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface135_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface136_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface137_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface138_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface139_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface140_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface141_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface142_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.t8_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface144_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface145_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface146_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface147_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface148_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface149_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface150_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface151_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface152_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface153_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface154_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface155_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface156_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface157_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface158_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface159_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface160_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface161_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface162_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface163_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface164_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface165_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface166_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface167_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface168_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface169_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface170_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface171_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface172_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface173_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface174_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface175_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface176_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface177_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface178_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface179_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface180_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface181_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface182_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface183_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface184_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface185_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface186_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface187_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface188_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface189_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface190_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface191_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface192_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface193_body_0.geometry}
            material={materials.body}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface194_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface195_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface196_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface197_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface198_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface199_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface200_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface201_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface202_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface203_body_0.geometry}
            material={materials.body}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface203_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface204_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface205_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface206_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface207_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface208_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface209_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface210_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface211_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface212_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface213_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface214_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface215_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface216_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface217_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface218_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface219_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface220_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface221_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface222_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface223_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface224_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface225_body_0.geometry}
            material={materials.body}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface226_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface227_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface228_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface229_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface230_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface231_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface232_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface233_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface234_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface235_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface236_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface237_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface238_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface239_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface240_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface241_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface242_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface243_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface244_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface245_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface246_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface247_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface248_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface249_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface250_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface251_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface252_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface253_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface254_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface255_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface256_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface257_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface258_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface259_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface260_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface261_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface262_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface263_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface264_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface265_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface266_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface267_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface268_body_0.geometry}
            material={materials.body}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface269_Numberplates_0.geometry}
            material={materials.Numberplates}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface270_UCB_GLASS_CLEAN_0.geometry}
            material={materials.UCB_GLASS_CLEAN}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface271_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface272_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface273_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface274_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface275_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface276_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface277_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface278_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface279_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface280_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface281_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface282_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface283_UCB_GLASS_CLEAN_0.geometry}
            material={materials.UCB_GLASS_CLEAN}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface284_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface285_UCB_GLASS_CLEAN_0.geometry}
            material={materials.UCB_GLASS_CLEAN}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface286_UCB_GLASS_CLEAN_0.geometry}
            material={materials.UCB_GLASS_CLEAN}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface287_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface288_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface289_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface290_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface291_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface292_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface293_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface294_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface295_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface296_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface297_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface298_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface299_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface300_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface301_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface302_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface303_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface304_GEN4DR_INTERIOR_0.geometry}
            material={materials.GEN4DR_INTERIOR}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface305_UCB_GLASS_CLEAN_0.geometry}
            material={materials.UCB_GLASS_CLEAN}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface306_body_0.geometry}
            material={materials.body}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface307_body_0.geometry}
            material={materials.body}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface308_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface309_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface310_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface311_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface312_Riverside88_lights_0.geometry}
            material={materials.Riverside88_lights}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface313_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface314_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface315_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface316_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface317_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface318_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface319_Numberplates_0.geometry}
            material={materials.Numberplates}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface325_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface326_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface327_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface328_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
          <mesh
            onPointerOver={(e) => handlePointerOver(e)}
            onPointerOut={handlePointerOut}
            geometry={nodes.polySurface329_UCB_BOTTOM_0.geometry}
            material={materials.UCB_BOTTOM}
          />
        </group>
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t9_blinn2_0.geometry}
          material={materials.blinn2}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t9_t2_0.geometry}
          material={materials.material}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t9_blinn3_0.geometry}
          material={materials.blinn3}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t9_blinn4_0.geometry}
          material={materials.blinn4}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t9_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.polySurface338_blinn2_0.geometry}
          material={materials.blinn2}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.polySurface338_blinn3_0.geometry}
          material={materials.blinn3}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.polySurface338_blinn4_0.geometry}
          material={materials.blinn4}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.polySurface338_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t7_blinn3_0.geometry}
          material={materials.blinn3}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t7_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t7_blinn2_0.geometry}
          material={materials.blinn2}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t7_blinn4_0.geometry}
          material={materials.blinn4}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t6_blinn3_0.geometry}
          material={materials.blinn3}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t6_blinn2_0.geometry}
          material={materials.blinn2}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t6_blinn4_0.geometry}
          material={materials.blinn4}
        />
        <mesh
          onPointerOver={(e) => handlePointerOver(e)}
          onPointerOut={handlePointerOut}
          geometry={nodes.t6_blinn1_0.geometry}
          material={materials.blinn1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/car_rig.glb");
